### ISSUE TITLE
Temperature Calculation from Si7051 Datasheet

### ISSUE THREAD

**Issue by Mduprie** [closedcube/ClosedCube_Si7051_Arduino#1]
In ClosedCube_Si7051.cpp

the line 

return (175.26*val) / 65536 - 46.85;

should be 

return (175.72*val) / 65536 - 46.85;

according to the Si7051 datasheet.

**Comment by closedcube** [comment]
Thank you for the reporting the issue, it was fixed now. (release 1.0.2)
